"use client"

import { TemplateResponse } from "@/lib/interfaces/templates.interface"
import {
  SandpackProvider,
  SandpackLayout,
  SandpackCodeEditor,
  SandpackPreview,
} from "@codesandbox/sandpack-react";
import { html } from "@codemirror/lang-html";
import { css } from "@codemirror/lang-css";
import { autocompletion, closeBrackets } from "@codemirror/autocomplete";
import {
  keymap, highlightActiveLine, highlightSpecialChars,
  highlightActiveLineGutter,
  highlightTrailingWhitespace,
  gutters,
  lineNumbers,
  EditorView,
  tooltips,
  rectangularSelection
} from "@codemirror/view";
import { indentWithTab, defaultKeymap } from "@codemirror/commands";
import SyncCode from "./syncCode";
import { Code2, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState } from "react";

const customAutocompleteTheme = EditorView.theme({
  ".cm-tooltip-autocomplete": {
    backgroundColor: "#1e1e1e",
    color: "#fff",
    border: "1px solid #444",
  },
  ".cm-tooltip-autocomplete .cm-completionLabel": {
    color: "#fff"
  },
  ".cm-tooltip-autocomplete .cm-completionMatchedText": {
    color: "#6cf"
  }
});

interface CustomCodeRendererProps {
  template: TemplateResponse
}

export function CustomCodeRenderer({ template }: CustomCodeRendererProps) {
  const [copiedHtml, setCopiedHtml] = useState(false)
  const [copiedCss, setCopiedCss] = useState(false)

  const copyToClipboard = async (code: string, type: 'html' | 'css') => {
    await navigator.clipboard.writeText(code)
    if (type === 'html') {
      setCopiedHtml(true)
      setTimeout(() => setCopiedHtml(false), 2000)
    } else {
      setCopiedCss(true)
      setTimeout(() => setCopiedCss(false), 2000)
    }
  }

  return (
    <SandpackProvider
      template="vanilla"
      theme="dark"
      files={{
        "/index.html": {
          active: true,
          code: template.raw_text?.html || `<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body>
     <div class="pinglet">

   <!-- Add your custom HTML here, DO NOT REMOVE THE '.pinglet' DIV -->

 
    </div>
  </body>
</html>
`,
        },
        "/style.css": {
          code: template.raw_text?.css || `.pinglet {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: #f5f7fa;
            padding: 2rem;
            line-height: 1.5;
        }
          /* Add your custom CSS here, DO NOT REMOVE THE '.pinglet' CLASS */
`,
        },
        "/index.js": { code: "// Do not edit this file", readOnly: true },
      }}
      customSetup={{
        entry: "/index.html",
      }}
    >
      <div className="space-y-6 p-8">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto">
          <div className="inline-flex items-center justify-center p-3 rounded-2xl bg-gradient-to-br from-green-500/20 to-emerald-500/10 mb-4">
            <Code2 className="w-8 h-8 text-green-600 dark:text-green-400" />
          </div>
          <h2 className="text-3xl font-bold bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent mb-3">
            {template.name} - Custom Code
          </h2>
          <p className="text-lg text-muted-foreground">
            View and edit the source code for this template
          </p>
        </div>

        {/* Code Editor */}
        <div className="bg-card border-2 border-border/50 rounded-2xl overflow-hidden shadow-xl">
          {/* Editor Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-border/50 bg-gradient-to-r from-muted/50 to-muted/30 backdrop-blur-sm">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-primary/10">
                <Code2 className="w-5 h-5 text-primary" />
              </div>
              <div>
                <h3 className="text-sm font-semibold text-foreground">Code Editor</h3>
                <p className="text-xs text-muted-foreground">HTML & CSS</p>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <Button
                onClick={() => copyToClipboard(template.raw_text?.html || "", 'html')}
                variant="outline"
                size="sm"
                className="gap-2 rounded-xl border-border/50 bg-background/50 hover:bg-primary/10 hover:border-primary/50 transition-all duration-200"
              >
                {copiedHtml ? (
                  <>
                    <Check className="w-4 h-4 text-green-600" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    Copy HTML
                  </>
                )}
              </Button>

              <Button
                onClick={() => copyToClipboard(template.raw_text?.css || "", 'css')}
                variant="outline"
                size="sm"
                className="gap-2 rounded-xl border-border/50 bg-background/50 hover:bg-primary/10 hover:border-primary/50 transition-all duration-200"
              >
                {copiedCss ? (
                  <>
                    <Check className="w-4 h-4 text-green-600" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    Copy CSS
                  </>
                )}
              </Button>

              <SyncCode />
            </div>
          </div>

          {/* Sandpack Editor */}
          <div className="relative">
            <SandpackLayout>
              <SandpackCodeEditor
                showTabs
                extensions={[
                  highlightActiveLine(),
                  highlightSpecialChars(),
                  autocompletion(),
                  closeBrackets(),
                  keymap.of([indentWithTab]),
                  keymap.of([...defaultKeymap]),
                  html(),
                  css(),
                  customAutocompleteTheme,
                  highlightActiveLineGutter(),
                  highlightTrailingWhitespace(),
                  lineNumbers(),
                  gutters(),
                  tooltips(),
                  rectangularSelection()
                ]}
                showInlineErrors
                showLineNumbers
                wrapContent
                readOnly
                showReadOnly
                style={{ height: 600 }}
              />
              <SandpackPreview
                style={{ height: 600 }}
                showOpenInCodeSandbox={false}
                showRefreshButton={true}
              />
            </SandpackLayout>
          </div>
        </div>
      </div>
    </SandpackProvider>
  )
}
